name: Hello World!

on:
  push:
    branches:
      - master
       pull_request:
    branches: [master]
    types: [opened, synchronize] 
    
      # note that your "main" branch might be called main instead of master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"

          if: ${{ github.event_name == 'push' }}

 - name: Bump version and push tag
  uses: anothrNick/github-tag-action@1.55.0
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
