name: Deployment pipeline

on:
  push:
    branches:
      - master 
  pull_request:
    branches: [master]
    types: [opened, synchronize]
      
      # note that your "main" branch might be called main instead of master

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      // steps here
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      // steps here
     with:
       node-version: '16'
      - name: Install dependencies 
        run: npm install  
      - name: Check style
        run: npm run eslint

